### ISSUE TITLE
TODO part

### ISSUE THREAD

**Issue by maxrdu** [Concerned-Coyotes/summer-code-jam-2020#40]
- [x] Todo model with connection to user
- [x] Todo edit view
- [x] Todo add view
- [x] Testing for the model
- [x] Testing for the frontend

**Comment by maxrdu** [comment]
Testing cannot be done unless the authentication is in place
